?condition: or_cond

?or_cond: or_cond "or" and_cond  -> or
        | and_cond

?and_cond: and_cond "and" not_cond -> and
         | not_cond

?not_cond: "not" not_cond          -> not
         | cmp_cond

?cmp_cond: expr ">" expr   -> gt
         | expr "<" expr   -> lt
         | expr "=" expr   -> eq
         | expr GE expr    -> ge
         | expr LE expr    -> le
         | expr NE expr    -> ne
         | "(" condition ")"

%import .expressions (expr)
%import .tokens (GE, LE, NE)