start: program

program: tokens*

tokens: KEYWORD
        | WORD
        | TYPE
        | NUMBER
        | STRING

KEYWORD.2: "fun"
        | "while"
        | "for"
        | "if"
        | "var"
        | "val"
        | "else"
        | "return"
        | "true"
        | "false"

WORD: /[a-zA-Z_][a-zA-Z0-9_]*/
        |"+" | "-" | "/" | "*" | "+=" | "-=" | "*=" | "/=" | ">" | "<" | ">=" | "<=" | "==" | "!=" | "="
        | "[" | "]" | "{" | "}" | "(" | ")"
        | ";" | ":" | ","

STRING: /"[^"]*"/

TYPE.2: "Int"
        | "Byte"
        | "Short"
        | "Long"
        | "Float"
        | "Double"
        | "Boolean"
        | "Char"
        | "String"


%import common.WS
%ignore WS
%import common.NUMBER
